# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  bdlabo0201vaccin:
    image: bdlabo0201vaccin
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000
      - 5001
